version: "3"
services:
  pagila:
    image: postgres:16.4
    container_name: pagila
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
    volumes:
      - ./pagila-schema.sql:/docker-entrypoint-initdb.d/1-pagila-schema.sql
      - ./pagila-data.sql:/docker-entrypoint-initdb.d/2-pagila-data.sql
    expose:
      - 5432
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
  jupyter-spark:
    image: jupyter/pyspark-notebook
    ports:
      - "8888:8888"
    volumes:
      - ./postgresql-42.7.4.jar:/jars/postgresql-42.7.4.jar
